# Generated by Django 3.2.3 on 2022-06-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_beu_delivery_bot', '0002_auto_20220615_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
